version: '3.8'

services:
  registry:
    image: registry:3
    restart: always
    env_file:
      - ./.env
    environment:
      # Disable OpenTelemetry traces/metrics exporter to avoid attempts to connect to localhost:4318
      - OTEL_TRACES_EXPORTER=none
      - OTEL_METRICS_EXPORTER=none
      # Reduce log verbosity (possible values: debug, info, warn, error)
      - LOG_LEVEL=info
    volumes:
      # Mount volume for image persistence
      - ./data:/var/lib/registry
    networks:
      - registry-net

  nginx:
    image: nginx:latest
    restart: always
    ports:
      # Expose HTTPS port 443 to the outside world (host:container)
      - "${NGINX_PORT}:443"
    volumes:
      # Mount NGINX configuration and certificates
      - ./nginx/registry.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - registry
    networks:
      - registry-net

networks:
  registry-net:
