version: '3.8'

services:
  registry:
    image: registry:3
    restart: always
    volumes:
      # Mapea el volumen para persistencia de las imágenes
      - ./data:/var/lib/registry
    networks:
      - registry-net

  nginx:
    image: nginx:latest
    restart: always
    ports:
      # Expone el puerto 443 (HTTPS) al mundo exterior
      - "${NGINX_PORT}:443"
    volumes:
      # Mapea la configuración de NGINX y los certificados
      # Template que será procesada en tiempo de arranque
      - ./nginx/registry.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./certs:/etc/nginx/certs
      # Entry point script para sustituir variables y arrancar nginx
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
    env_file:
      - ./.env
    command: ["/bin/sh", "/docker-entrypoint.sh"]
    depends_on:
      - registry
    networks:
      - registry-net

networks:
  registry-net:
